export type Language = "en" | "te" | "hi";
export const copy = {
  en: {
    home:"Home", schemes:"Find schemes", eligibility:"Check eligibility", assistant:"Ask a question", about:"About", admin:"Demo admin",
    language:"Language", larger:"Larger text", contrast:"High contrast", tagline:"Clear guidance for public services",
    heroKicker:"A little help, a clearer next step", heroTitle:"Government schemes, explained simply.", heroText:"Find public programmes that may fit your life, understand what to prepare, and know where to ask next.",
    browse:"Browse schemes", start:"Check what may fit", search:"Search by need or scheme name", categoryBrowse:"Browse by what you need", featured:"A good place to begin", allSchemes:"Explore all schemes",
    disclaimer:"GramaSeva is a guidance tool, not an official government service. Examples may be demo data. Please verify details with the relevant department before applying.",
    demo:"Demo information", verified:"Source marked verified", updated:"Information last updated", benefits:"What it may offer", documents:"What you may need", steps:"Possible next steps", report:"Report outdated information", reportTitle:"Help us keep this useful", reportPlaceholder:"What seems outdated or incorrect?", send:"Send report", cancel:"Cancel", reportThanks:"Thank you. Your report has been received.",
    loading:"Loading information…", loadError:"We couldn't load this information.", retry:"Try again", noResults:"No schemes found yet", noResultsHint:"Try a different word or remove a filter.", results:"schemes to explore", category:"Category", anyCategory:"All categories", searchNow:"Search", sort:"Sort", relevant:"Most relevant", alphabetical:"A to Z",
    eligibilityTitle:"A starting point, made for you.", eligibilityText:"Share a little about your situation. We’ll show schemes that may be relevant—not a final eligibility decision.",
    age:"Age", state:"State", occupation:"Occupation", annualIncome:"Approx. yearly household income (₹)", gender:"Gender", genderPlaceholder:"Choose if you wish", rural:"I live in a rural area", farmer:"I work in farming", student:"I am a student", disability:"I have a disability", senior:"I am a senior citizen", housing:"I need housing support", employment:"Employment status", check:"Show possible matches", matches:"Possible matches", noMatches:"No likely matches found", noMatchesHint:"You can still browse all schemes or ask a question.", reasons:"Why this may fit",
    askTitle:"Ask in your own words.", askText:"Ask about a benefit, documents, or how to begin. Answers use the scheme information available here.", askPlaceholder:"For example: Is there support for a small farmer?", sendQuestion:"Ask", listen:"Speak your question", stopListening:"Stop listening", speakAnswer:"Read answer aloud", voiceUnavailable:"Voice input is not available in this browser. You can type your question instead.", speechUnavailable:"Spoken answers are not available in this browser.", answer:"Answer", related:"Related schemes", thinking:"Looking through scheme information…", askError:"We couldn't get an answer just now. Please try again.",
    aboutTitle:"Public information should be easier to use.", problem:"The challenge", solution:"A simpler path", impact:"Designed for everyday access", problemText:"Scheme information can be spread across notices, forms and websites. It may be hard to know what applies or what to do first.", solutionText:"GramaSeva brings scheme summaries, possible requirements and next steps into one plain-language guide, with English, Telugu and Hindi.", impactText:"Large readable text, simple navigation and voice support help more people take a confident next step. It offers guidance, never a guarantee.",
    aboutNote:"This demonstration uses information provided through its connected scheme service. It is not an official government website and does not decide eligibility.",
    adminTitle:"Scheme information desk", adminIntro:"A demonstration workspace for maintaining the scheme guide.", total:"Total records", active:"Active", categories:"Categories", addScheme:"Add a scheme", edit:"Edit", deactivate:"Deactivate", activate:"Activate", save:"Save scheme", name:"Scheme name", summary:"Short summary", description:"Description", benefitsLines:"Benefits (one per line)", documentsLines:"Documents (one per line)", stepsLines:"Application steps (one per line)", keywords:"Search keywords (comma separated)", source:"Information source", demoSource:"Demo", verifiedSource:"Verified", officialUrl:"Official URL (optional)", saveSuccess:"Scheme information saved.", adminError:"Could not save this scheme. Please check the fields and try again.", noAdmin:"No scheme records are available.", close:"Close", status:"Status", activeStatus:"Active", inactiveStatus:"Inactive",
    notFound:"We couldn't find that page.", returnHome:"Return to home", footer:"Made to make the next step clearer.", menu:"Main navigation", resultLabel:"Scheme results", choose:"Choose", yes:"Yes", no:"No", incomeLabel:"Household income per year",
    demoAdminAccess:"Demo admin access", demoSignInTitle:"Sign in to manage scheme records", demoSignInBody:"This protected demonstration area lets an administrator update, add or deactivate the scheme information shown in GramaSeva.", accessCode:"Demo access code", signInDemo:"Sign in to demo admin", signOut:"Sign out", badPassword:"That demo access code was not accepted. Try again.", authUnavailable:"Demo sign-in is unavailable. Try again later.", actions:"Actions", listedSource:"View listed source", serviceChecking:"Checking information service…", serviceUnavailable:"Information service status unavailable", serviceName:"Information service", english:"English", telugu:"తెలుగు", hindi:"हिन्दी", employed:"Employed", unemployed:"Unemployed", selfEmployed:"Self-employed", adminFootnote:"Demo access only. Scheme data remains connected to the API service.", assistantTip:"Ask one thing at a time. A person at your local service centre can help confirm details.", households:"Information for every household"
  },
  te: {
    home:"హోమ్", schemes:"పథకాలు కనుగొనండి", eligibility:"అర్హత చూడండి", assistant:"ప్రశ్న అడగండి", about:"మా గురించి", admin:"డెమో నిర్వాహకుడు",
    language:"భాష", larger:"పెద్ద అక్షరాలు", contrast:"అధిక కాంట్రాస్ట్", tagline:"ప్రజా సేవలకు స్పష్టమైన మార్గదర్శకం",
    heroKicker:"కొంచెం సహాయం, స్పష్టమైన తదుపరి అడుగు", heroTitle:"ప్రభుత్వ పథకాలు. సులభంగా అర్థం చేసుకోండి.", heroText:"మీ జీవితానికి సరిపడవచ్చే పథకాలను కనుగొనండి, సిద్ధం చేసుకోవాల్సినవి తెలుసుకోండి, ఎక్కడ అడగాలో తెలుసుకోండి.",
    browse:"పథకాలను చూడండి", start:"మీకు సరిపోవచ్చేవి చూడండి", search:"అవసరం లేదా పథకం పేరుతో వెతకండి", categoryBrowse:"మీ అవసరాన్ని ఎంచుకోండి", featured:"ఇక్కడ మొదలుపెట్టండి", allSchemes:"అన్ని పథకాలు",
    disclaimer:"గ్రామసేవ మార్గదర్శక సాధనం మాత్రమే; ఇది ప్రభుత్వ సేవ కాదు. కొన్ని వివరాలు డెమో కావచ్చు. దరఖాస్తుకు ముందు సంబంధిత శాఖతో వివరాలు నిర్ధారించుకోండి.",
    demo:"డెమో సమాచారం", verified:"ధృవీకరించిన మూలంగా గుర్తింపు", updated:"చివరిగా నవీకరించిన తేదీ", benefits:"లభించవచ్చేవి", documents:"అవసరమయ్యేవి", steps:"తదుపరి అడుగులు", report:"పాత సమాచారాన్ని తెలియజేయండి", reportTitle:"ఈ సమాచారాన్ని మెరుగ్గా ఉంచేందుకు సహాయపడండి", reportPlaceholder:"ఏది తప్పు లేదా పాతది అనిపిస్తోంది?", send:"నివేదిక పంపండి", cancel:"రద్దు చేయి", reportThanks:"ధన్యవాదాలు. మీ నివేదిక అందింది.",
    loading:"సమాచారం లోడ్ అవుతోంది…", loadError:"ఈ సమాచారాన్ని లోడ్ చేయలేకపోయాం.", retry:"మళ్లీ ప్రయత్నించండి", noResults:"పథకాలు కనబడలేదు", noResultsHint:"మరో పదంతో వెతకండి లేదా ఫిల్టర్ తొలగించండి.", results:"పథకాలు", category:"వర్గం", anyCategory:"అన్ని వర్గాలు", searchNow:"వెతకండి", sort:"క్రమం", relevant:"సంబంధితవి", alphabetical:"అక్షరక్రమం",
    eligibilityTitle:"మీ కోసం ఒక ప్రారంభ సూచన.", eligibilityText:"మీ పరిస్థితి గురించి కొద్దిగా చెప్పండి. తుది అర్హత నిర్ణయం కాదు—సంబంధితంగా ఉండవచ్చే పథకాలను చూపిస్తాం.",
    age:"వయస్సు", state:"రాష్ట్రం", occupation:"వృత్తి", annualIncome:"సంవత్సర కుటుంబ ఆదాయం (₹)", gender:"లింగం", genderPlaceholder:"ఇష్టమైతే ఎంచుకోండి", rural:"నేను గ్రామీణ ప్రాంతంలో నివసిస్తున్నాను", farmer:"నేను వ్యవసాయం చేస్తాను", student:"నేను విద్యార్థిని", disability:"నాకు వైకల్యం ఉంది", senior:"నేను సీనియర్ పౌరుడిని", housing:"నాకు గృహ సహాయం అవసరం", employment:"ఉద్యోగ స్థితి", check:"సాధ్యమైన పథకాలు చూపించండి", matches:"సాధ్యమైన పథకాలు", noMatches:"సంబంధిత పథకాలు కనబడలేదు", noMatchesHint:"అన్ని పథకాలను చూడవచ్చు లేదా ప్రశ్న అడగవచ్చు.", reasons:"ఇది ఎందుకు సరిపోవచ్చు",
    askTitle:"మీ మాటల్లో ప్రశ్న అడగండి.", askText:"ప్రయోజనం, పత్రాలు లేదా ఎలా మొదలుపెట్టాలి అని అడగండి. అందుబాటులో ఉన్న పథక సమాచారంతో సమాధానాలు ఇస్తాం.", askPlaceholder:"ఉదా: చిన్న రైతులకు సహాయం ఉందా?", sendQuestion:"అడగండి", listen:"ప్రశ్న మాట్లాడండి", stopListening:"వినడం ఆపండి", speakAnswer:"సమాధానం వినండి", voiceUnavailable:"ఈ బ్రౌజర్‌లో వాయిస్ ఇన్‌పుట్ లేదు. ప్రశ్న టైప్ చేయండి.", speechUnavailable:"ఈ బ్రౌజర్‌లో సమాధానాన్ని వినే సౌకర్యం లేదు.", answer:"సమాధానం", related:"సంబంధిత పథకాలు", thinking:"పథకాల సమాచారం చూస్తున్నాం…", askError:"ఇప్పుడే సమాధానం పొందలేకపోయాం. మళ్లీ ప్రయత్నించండి.",
    aboutTitle:"ప్రజా సమాచారం అందరికీ సులభంగా ఉండాలి.", problem:"సవాలు", solution:"సులభమైన మార్గం", impact:"రోజువారీ వినియోగం కోసం", problemText:"పథకాల సమాచారం ప్రకటనలు, ఫారాలు, వెబ్‌సైట్లలో విస్తరించి ఉంటుంది. ఏది వర్తిస్తుందో, మొదట ఏమి చేయాలో అర్థం చేసుకోవడం కష్టం.", solutionText:"గ్రామసేవ పథకాల సారాంశాలు, సాధ్యమైన అవసరాలు, తదుపరి అడుగులను ఇంగ్లీష్, తెలుగు, హిందీలో సులభంగా అందిస్తుంది.", impactText:"పెద్ద అక్షరాలు, సులభ నావిగేషన్, వాయిస్ మద్దతుతో మరింత మంది తదుపరి అడుగు వేయగలరు. ఇది మార్గదర్శకం మాత్రమే; హామీ కాదు.",
    aboutNote:"ఈ డెమో దాని పథక సేవ ద్వారా అందించిన సమాచారాన్ని ఉపయోగిస్తుంది. ఇది ప్రభుత్వ వెబ్‌సైట్ కాదు, అర్హతను నిర్ణయించదు.",
    adminTitle:"పథకాల సమాచార కేంద్రం", adminIntro:"పథక మార్గదర్శకాన్ని నిర్వహించేందుకు డెమో వర్క్‌స్పేస్.", total:"మొత్తం రికార్డులు", active:"క్రియాశీలం", categories:"వర్గాలు", addScheme:"పథకం జోడించండి", edit:"సవరించండి", deactivate:"నిలిపివేయండి", activate:"ప్రారంభించండి", save:"పథకం భద్రపరచండి", name:"పథకం పేరు", summary:"సంక్షిప్త వివరణ", description:"వివరణ", benefitsLines:"ప్రయోజనాలు (ఒక్కో లైనులో)", documentsLines:"పత్రాలు (ఒక్కో లైనులో)", stepsLines:"దరఖాస్తు దశలు (ఒక్కో లైనులో)", keywords:"కీవర్డ్లు (కామాలతో)", source:"సమాచార మూలం", demoSource:"డెమో", verifiedSource:"ధృవీకరించబడింది", officialUrl:"అధికారిక URL (ఐచ్ఛికం)", saveSuccess:"పథక సమాచారం భద్రపరచబడింది.", adminError:"ఈ పథకాన్ని భద్రపరచలేకపోయాం.", noAdmin:"పథక రికార్డులు అందుబాటులో లేవు.", close:"మూసివేయండి", status:"స్థితి", activeStatus:"క్రియాశీలం", inactiveStatus:"నిలిపివేశారు",
    notFound:"ఆ పేజీ కనబడలేదు.", returnHome:"హోమ్‌కు తిరిగి వెళ్లండి", footer:"తదుపరి అడుగును స్పష్టంగా చేయడానికి.", menu:"ప్రధాన నావిగేషన్", resultLabel:"పథక ఫలితాలు", choose:"ఎంచుకోండి", yes:"అవును", no:"కాదు", incomeLabel:"వార్షిక కుటుంబ ఆదాయం",
    demoAdminAccess:"డెమో నిర్వాహకుడి ప్రవేశం", demoSignInTitle:"పథక రికార్డులను నిర్వహించడానికి ప్రవేశించండి", demoSignInBody:"ఈ రక్షిత డెమో ప్రాంతంలో నిర్వాహకుడు గ్రామసేవలో చూపించే పథక సమాచారాన్ని జోడించవచ్చు లేదా సవరించవచ్చు.", accessCode:"డెమో ప్రవేశ కోడ్", signInDemo:"డెమో నిర్వాహకుడిగా ప్రవేశించండి", signOut:"నిష్క్రమించండి", badPassword:"డెమో కోడ్ సరిపోలలేదు. మళ్లీ ప్రయత్నించండి.", authUnavailable:"డెమో ప్రవేశం అందుబాటులో లేదు. తర్వాత ప్రయత్నించండి.", actions:"చర్యలు", listedSource:"మూలాన్ని చూడండి", serviceChecking:"సమాచార సేవను తనిఖీ చేస్తున్నాం…", serviceUnavailable:"సమాచార సేవ స్థితి అందుబాటులో లేదు", serviceName:"సమాచార సేవ", english:"English", telugu:"తెలుగు", hindi:"हिन्दी", employed:"ఉద్యోగి", unemployed:"నిరుద్యోగి", selfEmployed:"స్వయం ఉపాధి", adminFootnote:"డెమో ప్రవేశం మాత్రమే. పథక డేటా API సేవకే అనుసంధానించబడింది.", assistantTip:"ఒకేసారి ఒక్క ప్రశ్న అడగండి. స్థానిక సేవా కేంద్రంలో వివరాలు నిర్ధారించుకోవచ్చు.", households:"ప్రతి ఇంటికీ సమాచారం"
  },
  hi: {
    home:"मुखपृष्ठ", schemes:"योजनाएँ खोजें", eligibility:"पात्रता देखें", assistant:"सवाल पूछें", about:"हमारे बारे में", admin:"डेमो व्यवस्थापक",
    language:"भाषा", larger:"बड़ा अक्षर", contrast:"ज़्यादा कंट्रास्ट", tagline:"जन सेवाओं के लिए साफ़ मार्गदर्शन",
    heroKicker:"थोड़ी मदद, अगला कदम साफ़", heroTitle:"सरकारी योजनाएँ, आसान भाषा में।", heroText:"अपने जीवन से जुड़ी योजनाएँ खोजें, तैयारी समझें और जानें कि आगे कहाँ पूछना है।",
    browse:"योजनाएँ देखें", start:"अपने लिए संभावित योजनाएँ देखें", search:"ज़रूरत या योजना के नाम से खोजें", categoryBrowse:"ज़रूरत के अनुसार देखें", featured:"शुरुआत यहाँ से करें", allSchemes:"सभी योजनाएँ देखें",
    disclaimer:"ग्रामसेवा केवल जानकारी देने का साधन है, सरकारी सेवा नहीं। कुछ जानकारी डेमो हो सकती है। आवेदन से पहले संबंधित विभाग से पुष्टि करें।",
    demo:"डेमो जानकारी", verified:"स्रोत सत्यापित के रूप में चिह्नित", updated:"जानकारी आख़िरी बार अपडेट", benefits:"क्या लाभ मिल सकता है", documents:"क्या चाहिए हो सकता है", steps:"आगे के संभावित कदम", report:"पुरानी जानकारी की सूचना दें", reportTitle:"जानकारी बेहतर रखने में मदद करें", reportPlaceholder:"क्या गलत या पुराना लग रहा है?", send:"रिपोर्ट भेजें", cancel:"रद्द करें", reportThanks:"धन्यवाद। आपकी रिपोर्ट मिल गई है।",
    loading:"जानकारी लोड हो रही है…", loadError:"जानकारी लोड नहीं हो सकी।", retry:"फिर कोशिश करें", noResults:"कोई योजना नहीं मिली", noResultsHint:"दूसरे शब्द से खोजें या फ़िल्टर हटाएँ।", results:"योजनाएँ", category:"श्रेणी", anyCategory:"सभी श्रेणियाँ", searchNow:"खोजें", sort:"क्रम", relevant:"सबसे प्रासंगिक", alphabetical:"वर्णमाला क्रम",
    eligibilityTitle:"आपके लिए एक शुरुआती संकेत।", eligibilityText:"अपनी स्थिति के बारे में थोड़ा बताएँ। हम संभावित योजनाएँ दिखाएँगे—यह अंतिम पात्रता का फैसला नहीं है।",
    age:"उम्र", state:"राज्य", occupation:"पेशा", annualIncome:"अनुमानित सालाना पारिवारिक आय (₹)", gender:"लिंग", genderPlaceholder:"चाहें तो चुनें", rural:"मैं ग्रामीण इलाके में रहता/रहती हूँ", farmer:"मैं खेती करता/करती हूँ", student:"मैं विद्यार्थी हूँ", disability:"मुझे दिव्यांगता है", senior:"मैं वरिष्ठ नागरिक हूँ", housing:"मुझे आवास सहायता चाहिए", employment:"रोज़गार की स्थिति", check:"संभावित योजनाएँ दिखाएँ", matches:"संभावित योजनाएँ", noMatches:"कोई संभावित योजना नहीं मिली", noMatchesHint:"सभी योजनाएँ देखें या सवाल पूछें।", reasons:"यह क्यों उपयुक्त हो सकती है",
    askTitle:"अपने शब्दों में सवाल पूछें।", askText:"लाभ, दस्तावेज़ या शुरुआत के बारे में पूछें। जवाब यहाँ उपलब्ध योजना जानकारी पर आधारित हैं।", askPlaceholder:"जैसे: छोटे किसान के लिए सहायता है?", sendQuestion:"पूछें", listen:"सवाल बोलें", stopListening:"सुनना बंद करें", speakAnswer:"जवाब सुनें", voiceUnavailable:"इस ब्राउज़र में आवाज़ से सवाल नहीं लिया जा सकता। आप टाइप कर सकते हैं।", speechUnavailable:"इस ब्राउज़र में जवाब सुनने की सुविधा नहीं है।", answer:"जवाब", related:"संबंधित योजनाएँ", thinking:"योजना की जानकारी देख रहे हैं…", askError:"अभी जवाब नहीं मिल सका। फिर कोशिश करें।",
    aboutTitle:"सार्वजनिक जानकारी सबके लिए आसान होनी चाहिए।", problem:"चुनौती", solution:"आसान रास्ता", impact:"रोज़मर्रा की पहुँच के लिए", problemText:"योजनाओं की जानकारी सूचनाओं, फ़ॉर्म और वेबसाइटों में बिखरी रहती है। क्या लागू है और पहले क्या करना है, समझना कठिन हो सकता है।", solutionText:"ग्रामसेवा योजना का सार, संभावित ज़रूरतें और अगले कदम सरल भाषा में अंग्रेज़ी, तेलुगु और हिंदी में रखता है।", impactText:"बड़े अक्षर, आसान रास्ते और आवाज़ की सुविधा ज़्यादा लोगों को अगला कदम उठाने में मदद करती है। यह मार्गदर्शन है, गारंटी नहीं।",
    aboutNote:"यह डेमो अपने जुड़े हुए योजना सेवा से मिली जानकारी का उपयोग करता है। यह सरकारी वेबसाइट नहीं है और पात्रता तय नहीं करता।",
    adminTitle:"योजना जानकारी केंद्र", adminIntro:"योजना मार्गदर्शिका सँभालने के लिए डेमो कार्यक्षेत्र।", total:"कुल रिकॉर्ड", active:"सक्रिय", categories:"श्रेणियाँ", addScheme:"योजना जोड़ें", edit:"बदलें", deactivate:"निष्क्रिय करें", activate:"सक्रिय करें", save:"योजना सहेजें", name:"योजना का नाम", summary:"छोटा सार", description:"विवरण", benefitsLines:"लाभ (हर पंक्ति में एक)", documentsLines:"दस्तावेज़ (हर पंक्ति में एक)", stepsLines:"आवेदन के कदम (हर पंक्ति में एक)", keywords:"खोज शब्द (कॉमा से अलग)", source:"जानकारी का स्रोत", demoSource:"डेमो", verifiedSource:"सत्यापित", officialUrl:"आधिकारिक URL (वैकल्पिक)", saveSuccess:"योजना की जानकारी सहेजी गई।", adminError:"योजना सहेजी नहीं जा सकी।", noAdmin:"योजना रिकॉर्ड उपलब्ध नहीं हैं।", close:"बंद करें", status:"स्थिति", activeStatus:"सक्रिय", inactiveStatus:"निष्क्रिय",
    notFound:"यह पृष्ठ नहीं मिला।", returnHome:"मुखपृष्ठ पर लौटें", menu:"मुख्य नेविगेशन", resultLabel:"योजना परिणाम", choose:"चुनें", yes:"हाँ", no:"नहीं", incomeLabel:"सालाना पारिवारिक आय", footer:"अगला कदम स्पष्ट बनाने के लिए।",
    demoAdminAccess:"डेमो व्यवस्थापक प्रवेश", demoSignInTitle:"योजना रिकॉर्ड सँभालने के लिए साइन इन करें", demoSignInBody:"इस सुरक्षित डेमो क्षेत्र में व्यवस्थापक ग्रामसेवा की योजना जानकारी बदल, जोड़ या निष्क्रिय कर सकता है।", accessCode:"डेमो प्रवेश कोड", signInDemo:"डेमो व्यवस्थापक में प्रवेश", signOut:"साइन आउट", badPassword:"डेमो कोड स्वीकार नहीं हुआ। फिर कोशिश करें।", authUnavailable:"डेमो प्रवेश अभी उपलब्ध नहीं है। बाद में कोशिश करें।", actions:"कार्रवाई", listedSource:"सूचीबद्ध स्रोत देखें", serviceChecking:"जानकारी सेवा जाँच रहे हैं…", serviceUnavailable:"जानकारी सेवा की स्थिति उपलब्ध नहीं", serviceName:"जानकारी सेवा", english:"English", telugu:"తెలుగు", hindi:"हिन्दी", employed:"रोज़गार में", unemployed:"बेरोज़गार", selfEmployed:"स्वरोज़गार", adminFootnote:"केवल डेमो प्रवेश। योजना डेटा API सेवा से जुड़ा है।", assistantTip:"एक बार में एक बात पूछें। स्थानीय सेवा केंद्र में जानकारी की पुष्टि कर सकते हैं।", households:"हर परिवार के लिए जानकारी"
  }
} satisfies Record<Language, Record<string, string>>;
