import { createContext, useContext, useMemo, useState, type FormEvent, type ReactNode } from "react";
import { QueryClient, QueryClientProvider, useQueryClient } from "@tanstack/react-query";
import { Link, Route, Switch, useLocation, Router as WouterRouter } from "wouter";
import {
  ArrowDown, ArrowRight, ArrowUpRight, BookOpen, Check, ChevronDown, CircleHelp, ClipboardList,
  FileText, Filter, HandHeart, HeartHandshake, Home as HomeIcon, Info, Languages, LoaderCircle,
  MapPin, Menu, Mic, Search, ShieldCheck, Sparkles, Volume2, X
} from "lucide-react";
import {
  getGetAdminSessionQueryKey as getAdminSessionQueryKey, getGetAdminSummaryQueryKey,
  getGetCategoriesQueryKey, getGetSchemesByCategoryQueryKey, getListAdminSchemesQueryKey, getListSchemesQueryKey,
  getSearchSchemesQueryKey, useAskAssistant, useCheckEligibility, useCreateScheme, useDeactivateScheme,
  useGetAdminSession, useGetAdminSummary, useGetCategories, useGetScheme, useGetSchemesByCategory,
  useHealthCheck, useListAdminSchemes, useListSchemes, useLoginAdmin, useLogoutAdmin,
  useReportSchemeInformation, useSearchSchemes, useUpdateScheme
} from "@workspace/api-client-react";
import type { AdminLoginInput, Category, EligibilityInput, EligibilityMatch, Scheme, SchemeInput } from "@workspace/api-client-react";
import { copy, type Language } from "@/lib/translations";

const qc = new QueryClient();
type UiContextValue = { lang: Language; setLang:(l:Language)=>void; large:boolean; setLarge:(v:boolean)=>void; contrast:boolean; setContrast:(v:boolean)=>void };
const UiContext = createContext<UiContextValue | null>(null);
function useUi(){ const value=useContext(UiContext); if(!value) throw new Error("UI context missing"); return value; }
function useText(){ const {lang}=useUi(); return copy[lang]; }
const langName:Record<Language,string>={en:"English",te:"తెలుగు",hi:"हिन्दी"};
const localized=(s:Scheme,lang:Language,field:"name"|"summary"|"description")=>lang==="te"?(s[`${field}Te` as keyof Scheme] as string)||s[field]:lang==="hi"?(s[`${field}Hi` as keyof Scheme] as string)||s[field]:s[field];
const navItems=[["/","home",HomeIcon],["/schemes","schemes",BookOpen],["/eligibility","eligibility",ClipboardList],["/assistant","assistant",CircleHelp],["/about","about",Info]] as const;

function Shell({children}:{children:ReactNode}) {
  const t=useText(),{lang,setLang,large,setLarge,contrast,setContrast}=useUi(); const [menu,setMenu]=useState(false); const [loc]=useLocation();
  return <div className={`app-shell ${large?"large-type":""} ${contrast?"high-contrast":""}`}>
    <header className="topbar">
      <div className="topbar-inner">
        <Link href="/" className="brand" data-testid="link-brand"><span className="brand-mark"><HandHeart size={25}/></span><span><b>GramaSeva</b><small>{t.tagline}</small></span></Link>
        <button className="mobile-menu" aria-label={t.menu} onClick={()=>setMenu(!menu)} data-testid="button-menu">{menu?<X/>:<Menu/>}</button>
        <nav className={`main-nav ${menu?"nav-open":""}`} aria-label={t.menu}>
          {navItems.map(([href,key,Icon])=><Link key={href} href={href} onClick={()=>setMenu(false)} className={`nav-link ${loc===href?"nav-active":""}`} data-testid={`link-nav-${key}`}><Icon size={17}/><span>{t[key]}</span></Link>)}
        </nav>
        <div className="header-tools">
          <label className="language-select"><Languages size={16}/><span className="sr-only">{t.language}</span><select value={lang} onChange={e=>setLang(e.target.value as Language)} aria-label={t.language} data-testid="select-language">{(["en","te","hi"] as Language[]).map(l=><option key={l} value={l}>{langName[l]}</option>)}</select><ChevronDown size={13}/></label>
          <details className="access-menu"><summary aria-label={t.larger} data-testid="button-accessibility">Aa</summary><div className="access-pop">
            <label><input type="checkbox" checked={large} onChange={e=>setLarge(e.target.checked)} data-testid="toggle-large-type"/> {t.larger}</label>
            <label><input type="checkbox" checked={contrast} onChange={e=>setContrast(e.target.checked)} data-testid="toggle-contrast"/> {t.contrast}</label>
          </div></details>
        </div>
      </div>
    </header>
    <main>{children}</main>
    <footer className="footer"><div className="footer-inner"><Link href="/" className="footer-brand"><HandHeart size={20}/> GramaSeva</Link><p>{t.footer}</p><p className="footer-disclaimer">{t.disclaimer}</p><Link href="/admin" className="admin-link" data-testid="link-admin">{t.admin}</Link></div></footer>
  </div>;
}

function Notice(){const t=useText();return <aside className="notice" data-testid="notice-disclaimer"><ShieldCheck size={19}/><p>{t.disclaimer}</p></aside>}
function Loading({label}:{label:string}){return <div className="state-box" role="status" data-testid="status-loading"><span className="skeleton-line"/><span className="skeleton-line short"/><p>{label}</p></div>}
function ErrorState({label,onRetry}:{label:string;onRetry:()=>void}){const t=useText();return <div className="state-box error-state" role="alert" data-testid="status-error"><p>{label}</p><button className="button secondary" onClick={onRetry} data-testid="button-retry">{t.retry}</button></div>}
function PageIntro({eyebrow,title,body}:{eyebrow:string;title:string;body?:string}){return <div className="page-intro page-enter"><span className="eyebrow">{eyebrow}</span><h1>{title}</h1>{body&&<p>{body}</p>}</div>}
function SchemeCard({scheme}:{scheme:Scheme}) {const {lang}=useUi();const t=useText();return <article className="scheme-card" data-testid={`card-scheme-${scheme.id}`}>
  <div className="scheme-card-top"><span className="category-pill">{scheme.category}</span><span className={`source-dot ${scheme.sourceType==="verified"?"is-verified":""}`}>{scheme.sourceType==="verified"?t.verified:t.demo}</span></div>
  <h3>{localized(scheme,lang,"name")}</h3><p>{localized(scheme,lang,"summary")}</p>
  <div className="scheme-card-foot"><span className="mini-meta"><MapPin size={14}/>{t.updated} {scheme.lastUpdated}</span><Link href={`/schemes/${scheme.id}`} className="text-link" data-testid={`link-scheme-${scheme.id}`}>{t.browse}<ArrowRight size={16}/></Link></div>
</article>}
function SchemeGrid({schemes}:{schemes:Scheme[]}){const t=useText();return schemes.length?<div className="scheme-grid" data-testid="list-schemes">{schemes.map(s=><SchemeCard key={s.id} scheme={s}/>)}</div>:<div className="empty-state" data-testid="status-empty"><div className="empty-icon"><Search/></div><h3>{t.noResults}</h3><p>{t.noResultsHint}</p></div>}

function Home(){const t=useText();const q=useListSchemes({sort:"relevance"});const cats=useGetCategories();const health=useHealthCheck();const [query,setQuery]=useState("");const [,setLoc]=useLocation();
 return <div className="page-enter">
  <section className="hero"><div className="hero-inner"><div className="hero-copy"><span className="eyebrow light">{t.heroKicker}</span><h1>{t.heroTitle}</h1><p>{t.heroText}</p>
   <form className="hero-search" onSubmit={e=>{e.preventDefault();setLoc(`/schemes${query?`?q=${encodeURIComponent(query)}`:""}`)}}><Search size={21}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder={t.search} aria-label={t.search} data-testid="input-home-search"/><button type="submit" aria-label={t.searchNow} data-testid="button-home-search"><ArrowRight/></button></form>
   <div className="hero-ctas"><Link href="/schemes" className="button cream" data-testid="link-browse-schemes">{t.browse}<ArrowRight size={18}/></Link><Link href="/eligibility" className="hero-text-link" data-testid="link-start-eligibility">{t.start}<ArrowUpRight size={16}/></Link></div>
  </div><div className="hero-art" aria-hidden="true"><div className="sun-disc"/><div className="landscape hill-back"/><div className="landscape hill-front"/><div className="art-building"><span/><span/><span/><div/></div><div className="art-path"/><div className="hero-stamp"><HeartHandshake size={25}/><span>సేవ<br/>सहायता<br/>Support</span></div></div></div><div className="hero-bottom"><span>01 / 03</span><span className="hero-rule"/><span>{t.households}</span></div></section>
  <div className="content-wrap"><div className={`service-status ${health.isError?"service-unavailable":""}`} role="status" data-testid="status-service"><span/>{health.isLoading?t.serviceChecking:health.isError?t.serviceUnavailable:`${t.serviceName} · ${health.data?.status||"connected"}`}</div><Notice/>
   <section className="section-block"><div className="section-heading"><div><span className="eyebrow">{t.categoryBrowse}</span><h2>{t.categoryBrowse}</h2></div><Link href="/schemes" className="text-link" data-testid="link-all-categories">{t.allSchemes}<ArrowRight size={17}/></Link></div>
    {cats.isLoading?<Loading label={t.loading}/>:cats.isError?<ErrorState label={t.loadError} onRetry={()=>cats.refetch()}/>:<div className="category-strip" data-testid="list-categories">{(cats.data||[]).map((cat:Category,i)=><Link href={`/schemes?category=${encodeURIComponent(cat.id)}`} className={`category-tile tone-${i%4}`} key={cat.id} data-testid={`link-category-${cat.id}`}><span className="category-symbol">{cat.icon||"+"}</span><span className="category-label">{cat.label}</span><span className="category-count">{cat.count} {t.results}</span><ArrowUpRight className="cat-arrow" size={17}/></Link>)}</div>}
   </section>
   <section className="section-block featured-section"><div className="section-heading"><div><span className="eyebrow">{t.featured}</span><h2>{t.featured}</h2></div><Link href="/schemes" className="text-link" data-testid="link-see-all">{t.allSchemes}<ArrowRight size={17}/></Link></div>{q.isLoading?<Loading label={t.loading}/>:q.isError?<ErrorState label={t.loadError} onRetry={()=>q.refetch()}/>:<SchemeGrid schemes={(q.data||[]).slice(0,3)}/>}</section>
   <section className="guidance-band"><div className="guidance-icon"><Sparkles size={25}/></div><div><span className="eyebrow">{t.eligibility}</span><h2>{t.eligibilityTitle}</h2><p>{t.eligibilityText}</p></div><Link href="/eligibility" className="button primary" data-testid="link-check-eligibility">{t.start}<ArrowRight size={17}/></Link></section>
  </div>
 </div>}

function Schemes(){const t=useText();const [loc,setLoc]=useLocation();const params=new URLSearchParams(window.location.search);const [q,setQ]=useState(params.get("q")||"");const [cat,setCat]=useState(params.get("category")||"");const [sort,setSort]=useState<"name"|"relevance">("relevance");const cats=useGetCategories();
 const queryValue=q.trim()||" ";const searchQuery=useSearchSchemes({q:queryValue},{query:{enabled:Boolean(q.trim()),queryKey:getSearchSchemesQueryKey({q:queryValue})}});
 const categoryQuery=useGetSchemesByCategory(cat||"__no-category__",{query:{enabled:Boolean(cat),queryKey:getGetSchemesByCategoryQueryKey(cat||"__no-category__")}});
 const list=useListSchemes({sort},{query:{enabled:!q.trim()&&!cat,queryKey:getListSchemesQueryKey({sort})}});
 const shown=q.trim()?(searchQuery.data||[]).filter(s=>!cat||s.category===cat):cat?(categoryQuery.data||[]):list.data||[];
 const loading=q.trim()?searchQuery.isLoading:cat?categoryQuery.isLoading:list.isLoading;
 const failed=q.trim()?searchQuery.isError:cat?categoryQuery.isError:list.isError;
 const refetch=q.trim()?searchQuery.refetch:cat?categoryQuery.refetch:list.refetch;
 const submit=(e:FormEvent)=>{e.preventDefault();setLoc(`/schemes${q?`?q=${encodeURIComponent(q)}`:""}`)};
 return <div className="content-wrap page-enter"><PageIntro eyebrow={t.schemes} title={t.allSchemes} body={t.disclaimer}/>
  <form className="browse-controls" onSubmit={submit}><label className="search-field"><Search/><span className="sr-only">{t.search}</span><input value={q} onChange={e=>setQ(e.target.value)} placeholder={t.search} data-testid="input-scheme-search"/></label><label className="select-field"><Filter size={17}/><span className="sr-only">{t.category}</span><select value={cat} onChange={e=>setCat(e.target.value)} data-testid="select-category"><option value="">{t.anyCategory}</option>{(cats.data||[]).map(c=><option key={c.id} value={c.id}>{c.label}</option>)}</select></label><label className="select-field"><span>{t.sort}</span><select value={sort} onChange={e=>setSort(e.target.value as "name"|"relevance")} data-testid="select-sort"><option value="relevance">{t.relevant}</option><option value="name">{t.alphabetical}</option></select></label><button className="button primary" type="submit" data-testid="button-search-schemes">{t.searchNow}</button></form>
  <div className="result-count" data-testid="text-scheme-count">{shown.length} {t.results}</div>
  {loading?<Loading label={t.loading}/>:failed?<ErrorState label={t.loadError} onRetry={()=>refetch()}/>:<SchemeGrid schemes={shown}/>}
 </div>}

function ReportDialog({schemeId,onClose}:{schemeId:string;onClose:()=>void}){const t=useText();const report=useReportSchemeInformation();const [message,setMessage]=useState("");const [done,setDone]=useState(false);
 return <div className="modal-backdrop" role="presentation" onClick={onClose}><section className="modal" role="dialog" aria-modal="true" aria-labelledby="report-title" onClick={e=>e.stopPropagation()}><button className="icon-button modal-close" onClick={onClose} aria-label={t.close} data-testid="button-close-report"><X/></button>{done?<><div className="success-mark"><Check/></div><h2>{t.reportThanks}</h2><button className="button primary" onClick={onClose} data-testid="button-finish-report">{t.close}</button></>:<><span className="eyebrow">{t.report}</span><h2 id="report-title">{t.reportTitle}</h2><form onSubmit={e=>{e.preventDefault();report.mutate({data:{schemeId,message}},{onSuccess:()=>setDone(true)})}}><textarea required minLength={3} maxLength={1000} rows={4} value={message} onChange={e=>setMessage(e.target.value)} placeholder={t.reportPlaceholder} data-testid="input-report-message"/>{report.isError&&<p className="form-error">{t.loadError}</p>}<div className="modal-actions"><button className="button secondary" type="button" onClick={onClose} data-testid="button-cancel-report">{t.cancel}</button><button className="button primary" disabled={report.isPending} data-testid="button-submit-report">{report.isPending?t.loading:t.send}</button></div></form></>}</section></div>}
function SchemeDetail({id}:{id:string}){const t=useText(),{lang}=useUi();const scheme=useGetScheme(id);const [report,setReport]=useState(false);
 if(scheme.isLoading)return <div className="content-wrap"><Loading label={t.loading}/></div>;
 if(scheme.isError||!scheme.data)return <div className="content-wrap"><ErrorState label={t.loadError} onRetry={()=>scheme.refetch()}/></div>;
 const s=scheme.data;const strings=(items:string[])=>items.map((x,i)=><li key={`${i}-${x}`}>{x}</li>);
 return <div className="content-wrap page-enter"><div className="breadcrumbs"><Link href="/schemes" className="text-link" data-testid="link-back-schemes">{t.schemes}</Link><span>/</span><span>{localized(s,lang,"name")}</span></div><header className="detail-head"><span className="category-pill">{s.category}</span><span className={`source-dot ${s.sourceType==="verified"?"is-verified":""}`}>{s.sourceType==="verified"?t.verified:t.demo}</span><h1>{localized(s,lang,"name")}</h1><p className="detail-summary">{localized(s,lang,"summary")}</p><span className="mini-meta">{t.updated}: {s.lastUpdated}</span></header><Notice/>
  <div className="detail-grid"><div className="detail-main"><section className="detail-section"><h2>{t.about||"About this scheme"}</h2><p>{localized(s,lang,"description")}</p></section><section className="detail-section"><h2>{t.benefits}</h2><ul className="check-list">{strings(s.benefits||[])}</ul></section><section className="detail-section"><h2>{t.steps}</h2><ol className="number-list">{strings(s.applicationSteps||[])}</ol></section></div><aside className="detail-aside"><div className="aside-card"><h3>{t.eligibility}</h3><p>{s.eligibilitySummary}</p><Link href="/eligibility" className="text-link" data-testid="link-eligibility-detail">{t.start}<ArrowRight size={16}/></Link></div><div className="aside-card"><h3>{t.documents}</h3><ul className="plain-list">{strings(s.documents||[])}</ul></div>{s.officialUrl&&<a href={s.officialUrl} target="_blank" rel="noreferrer" className="button secondary" data-testid="link-official-source"><ArrowUpRight size={16}/>{t.listedSource}</a>}</aside></div>
  <div className="report-row"><p>{t.disclaimer}</p><button className="text-link" onClick={()=>setReport(true)} data-testid="button-report-outdated">{t.report}<ArrowRight size={16}/></button></div>{report&&<ReportDialog schemeId={id} onClose={()=>setReport(false)}/>}
 </div>}

function Eligibility(){const t=useText(),{lang}=useUi();const action=useCheckEligibility();const [matches,setMatches]=useState<EligibilityMatch[]|null>(null);const [form,setForm]=useState<EligibilityInput>({rural:true});const fields: {key:keyof EligibilityInput;label:string;type:"text"|"number"}[]=[{key:"age",label:t.age,type:"number"},{key:"state",label:t.state,type:"text"},{key:"occupation",label:t.occupation,type:"text"},{key:"annualIncome",label:t.annualIncome,type:"number"}];
 const toggle=(key:keyof EligibilityInput)=>setForm(p=>({...p,[key]:!p[key]}));
 return <div className="content-wrap page-enter"><PageIntro eyebrow={t.eligibility} title={t.eligibilityTitle} body={t.eligibilityText}/><Notice/>
  <form className="eligibility-form" onSubmit={e=>{e.preventDefault();const clean={...form};Object.keys(clean).forEach(k=>{const key=k as keyof EligibilityInput;if(clean[key]===""||clean[key]===undefined)delete clean[key]});action.mutate({data:clean},{onSuccess:setMatches})}}>
   <div className="form-grid">{fields.map(f=><label className="field" key={f.key}><span>{f.label}</span><input type={f.type} min={f.type==="number"?0:undefined} max={f.key==="age"?120:undefined} value={(form[f.key] as string|number|undefined)??""} onChange={e=>setForm(p=>({...p,[f.key]:f.type==="number"?(e.target.value===""?undefined:Number(e.target.value)):e.target.value}))} data-testid={`input-eligibility-${f.key}`}/></label>)}</div>
   <div className="toggle-grid">{([[ "rural",t.rural],["farmer",t.farmer],["student",t.student],["disability",t.disability],["seniorCitizen",t.senior],["housingNeed",t.housing]] as [keyof EligibilityInput,string][]).map(([key,label])=><label className="check-row" key={key}><input type="checkbox" checked={Boolean(form[key])} onChange={()=>toggle(key)} data-testid={`check-eligibility-${key}`}/><span>{label}</span></label>)}</div>
   <div className="form-grid lower-fields"><label className="field"><span>{t.gender}</span><select value={form.gender||""} onChange={e=>setForm(p=>({...p,gender:e.target.value||undefined}))} data-testid="select-eligibility-gender"><option value="">{t.genderPlaceholder}</option><option value="female">{lang==="hi"?"महिला":lang==="te"?"స్త్రీ":"Female"}</option><option value="male">{lang==="hi"?"पुरुष":lang==="te"?"పురుషుడు":"Male"}</option><option value="other">{lang==="hi"?"अन्य":lang==="te"?"ఇతర":"Other"}</option></select></label><label className="field"><span>{t.employment}</span><select value={form.employmentStatus||""} onChange={e=>setForm(p=>({...p,employmentStatus:e.target.value||undefined}))} data-testid="select-employment-status"><option value="">{t.choose}</option><option value="employed">{t.employed}</option><option value="unemployed">{t.unemployed}</option><option value="self-employed">{t.selfEmployed}</option></select></label></div>
   <button className="button primary" disabled={action.isPending} data-testid="button-submit-eligibility">{action.isPending?<LoaderCircle className="spin"/>:null}{t.check}<ArrowRight size={17}/></button>
  </form>
  {action.isError&&<ErrorState label={t.loadError} onRetry={()=>action.mutate({data:form},{onSuccess:setMatches})}/>}
  {matches&&<section className="match-results" data-testid="section-eligibility-results"><div className="section-heading"><div><span className="eyebrow">{t.matches}</span><h2>{t.matches}</h2></div><span className="result-count">{matches.length}</span></div>{matches.length?matches.map((m,i)=><article className="match-card" key={m.scheme.id} data-testid={`card-match-${m.scheme.id}`}><div className="match-rank">{String(i+1).padStart(2,"0")}</div><div className="match-copy"><span className="category-pill">{m.scheme.category}</span><h3>{localized(m.scheme,lang,"name")}</h3><p>{localized(m.scheme,lang,"summary")}</p><b>{t.reasons}</b><ul>{m.reasons.map((r,j)=><li key={j}>{r}</li>)}</ul></div><div className="match-score">{Math.round(m.relevance)}<small>%</small><span>match</span><Link href={`/schemes/${m.scheme.id}`} className="text-link" data-testid={`link-match-${m.scheme.id}`}>{t.browse}<ArrowRight size={15}/></Link></div></article>):<div className="empty-state"><h3>{t.noMatches}</h3><p>{t.noMatchesHint}</p><Link href="/schemes" className="text-link" data-testid="link-browse-from-empty">{t.browse}<ArrowRight/></Link></div>}<p className="small-note">{t.disclaimer}</p></section>}
 </div>}

function Assistant(){const t=useText(),{lang}=useUi();const ask=useAskAssistant();const [message,setMessage]=useState("");const [voiceNote,setVoiceNote]=useState("");const recognition=useMemo(()=>{const w=window as Window&{SpeechRecognition?:new()=>any;webkitSpeechRecognition?:new()=>any};const C=w.SpeechRecognition||w.webkitSpeechRecognition;return C?new C():null},[]);
 const submit=(e:FormEvent)=>{e.preventDefault();if(message.trim())ask.mutate({data:{message:message.trim(),language:lang}},{onSuccess:(r)=>{if(!r.answer)setVoiceNote(t.askError)}})};
 const listen=()=>{if(!recognition){setVoiceNote(t.voiceUnavailable);return}setVoiceNote("");recognition.lang=lang==="te"?"te-IN":lang==="hi"?"hi-IN":"en-IN";recognition.onresult=(event:any)=>{setMessage(event.results[0][0].transcript)};recognition.onerror=()=>setVoiceNote(t.voiceUnavailable);recognition.start()};
 const speak=()=>{if(!("speechSynthesis" in window)){setVoiceNote(t.speechUnavailable);return}if(!ask.data?.answer)return;window.speechSynthesis.cancel();const utter=new SpeechSynthesisUtterance(ask.data.answer);utter.lang=lang==="te"?"te-IN":lang==="hi"?"hi-IN":"en-IN";window.speechSynthesis.speak(utter)};
 return <div className="content-wrap page-enter assistant-page"><PageIntro eyebrow={t.assistant} title={t.askTitle} body={t.askText}/><div className="assistant-layout"><section className="assistant-panel"><div className="assistant-panel-head"><span className="assistant-orb"><CircleHelp/></span><div><b>{t.assistant}</b><small>English · తెలుగు · हिन्दी</small></div></div><form onSubmit={submit}><label htmlFor="assistant-question">{t.askTitle}</label><textarea id="assistant-question" rows={4} maxLength={1000} value={message} onChange={e=>setMessage(e.target.value)} placeholder={t.askPlaceholder} data-testid="input-assistant-question"/><div className="assistant-controls"><button className="button secondary" type="button" onClick={listen} data-testid="button-voice-input"><Mic size={17}/>{t.listen}</button><button className="button primary" disabled={!message.trim()||ask.isPending} data-testid="button-ask-assistant">{ask.isPending?t.thinking:t.sendQuestion}<ArrowRight size={17}/></button></div></form>{voiceNote&&<p className="inline-note" role="status" data-testid="status-voice">{voiceNote}</p>}</section>
 <aside className="assistant-aside"><span className="eyebrow">{t.disclaimer.split(".")[0]}</span><p>{t.disclaimer}</p><div className="assistant-tip"><FileText/><span>{t.assistantTip}</span></div></aside></div>
 {ask.isPending&&<Loading label={t.thinking}/ >}{ask.isError&&<ErrorState label={t.askError} onRetry={()=>message.trim()&&ask.mutate({data:{message:message.trim(),language:lang}})}/>}
 {ask.data&&<section className="answer-panel" data-testid="panel-assistant-answer"><div className="answer-heading"><span className="eyebrow">{t.answer}</span><button className="button secondary" onClick={speak} data-testid="button-speak-answer"><Volume2 size={17}/>{t.speakAnswer}</button></div><p className="answer-text">{ask.data.answer}</p>{ask.data.schemes?.length>0&&<><h2>{t.related}</h2><SchemeGrid schemes={ask.data.schemes}/></>}</section>}</div>}

function About(){const t=useText();return <div className="content-wrap page-enter"><section className="about-hero"><span className="eyebrow">{t.about}</span><h1>{t.aboutTitle}</h1><p>{t.aboutNote}</p></section><div className="about-columns"><article className="about-card problem"><span className="about-index">01</span><span className="eyebrow">{t.problem}</span><h2>{t.problemText}</h2></article><article className="about-card solution"><span className="about-index">02</span><span className="eyebrow">{t.solution}</span><h2>{t.solutionText}</h2></article><article className="about-card impact"><span className="about-index">03</span><span className="eyebrow">{t.impact}</span><h2>{t.impactText}</h2></article></div><Notice/></div>}

const blankScheme=():SchemeInput=>({name:"",nameTe:"",nameHi:"",summary:"",summaryTe:"",summaryHi:"",description:"",descriptionTe:"",descriptionHi:"",category:"",benefits:[],eligibilitySummary:"",documents:[],applicationSteps:[],officialUrl:null,sourceType:"demo",keywords:[],active:true});
function AdminForm({initial,onClose,onSaved}:{initial:SchemeInput;onClose:()=>void;onSaved:(data:SchemeInput)=>void}) {const t=useText();const [data,setData]=useState(initial);const update=(k:keyof SchemeInput,v:unknown)=>setData(p=>({...p,[k]:v}));const listField=(k:"benefits"|"documents"|"applicationSteps",label:string)=><label className="field"><span>{label}</span><textarea rows={3} value={(data[k]||[]).join("\n")} onChange={e=>update(k,e.target.value.split("\n").filter(Boolean))} data-testid={`input-admin-${k}`}/></label>;
 return <form className="admin-form" onSubmit={e=>{e.preventDefault();onSaved(data)}}><div className="modal-head"><span className="eyebrow">{t.admin}</span><button type="button" className="icon-button" onClick={onClose} aria-label={t.close} data-testid="button-close-admin-form"><X/></button></div><h2>{initial.name?t.edit:t.addScheme}</h2><div className="form-grid"><label className="field"><span>{t.name} · {t.english}</span><input required maxLength={180} value={data.name} onChange={e=>update("name",e.target.value)} data-testid="input-admin-name"/></label><label className="field"><span>{t.name} · {t.telugu}</span><input value={data.nameTe} onChange={e=>update("nameTe",e.target.value)} data-testid="input-admin-name-te"/></label><label className="field"><span>{t.name} · {t.hindi}</span><input value={data.nameHi} onChange={e=>update("nameHi",e.target.value)} data-testid="input-admin-name-hi"/></label><label className="field"><span>{t.category}</span><input required value={data.category} onChange={e=>update("category",e.target.value)} data-testid="input-admin-category"/></label></div>
 <label className="field"><span>{t.summary} · {t.english}</span><textarea required maxLength={500} rows={2} value={data.summary} onChange={e=>update("summary",e.target.value)} data-testid="input-admin-summary"/></label><div className="form-grid"><label className="field"><span>{t.summary} · {t.telugu}</span><textarea maxLength={500} rows={2} value={data.summaryTe} onChange={e=>update("summaryTe",e.target.value)} data-testid="input-admin-summary-te"/></label><label className="field"><span>{t.summary} · {t.hindi}</span><textarea maxLength={500} rows={2} value={data.summaryHi} onChange={e=>update("summaryHi",e.target.value)} data-testid="input-admin-summary-hi"/></label></div><label className="field"><span>{t.description} · {t.english}</span><textarea rows={4} value={data.description} onChange={e=>update("description",e.target.value)} data-testid="input-admin-description"/></label><div className="form-grid"><label className="field"><span>{t.description} · {t.telugu}</span><textarea rows={3} value={data.descriptionTe} onChange={e=>update("descriptionTe",e.target.value)} data-testid="input-admin-description-te"/></label><label className="field"><span>{t.description} · {t.hindi}</span><textarea rows={3} value={data.descriptionHi} onChange={e=>update("descriptionHi",e.target.value)} data-testid="input-admin-description-hi"/></label></div><div className="form-grid">{listField("benefits",t.benefitsLines)}{listField("documents",t.documentsLines)}{listField("applicationSteps",t.stepsLines)}</div>
 <label className="field"><span>{t.eligibility}</span><textarea rows={2} value={data.eligibilitySummary} onChange={e=>update("eligibilitySummary",e.target.value)} data-testid="input-admin-eligibility"/></label><div className="form-grid"><label className="field"><span>{t.officialUrl}</span><input type="url" value={data.officialUrl||""} onChange={e=>update("officialUrl",e.target.value||null)} data-testid="input-admin-url"/></label><label className="field"><span>{t.source}</span><select value={data.sourceType} onChange={e=>update("sourceType",e.target.value)} data-testid="select-admin-source"><option value="demo">{t.demoSource}</option><option value="verified">{t.verifiedSource}</option></select></label></div><label className="field"><span>{t.keywords}</span><input value={(data.keywords||[]).join(", ")} onChange={e=>update("keywords",e.target.value.split(",").map(x=>x.trim()).filter(Boolean))} data-testid="input-admin-keywords"/></label><div className="modal-actions"><button type="button" className="button secondary" onClick={onClose} data-testid="button-cancel-admin">{t.cancel}</button><button className="button primary" data-testid="button-save-admin">{t.save}<Check size={17}/></button></div></form>}

function Admin(){const t=useText();const client=useQueryClient();const session=useGetAdminSession();const summary=useGetAdminSummary({query:{enabled:Boolean(session.data?.authenticated),queryKey:getGetAdminSummaryQueryKey()}});const records=useListAdminSchemes({query:{enabled:Boolean(session.data?.authenticated),queryKey:getListAdminSchemesQueryKey()}});const login=useLoginAdmin();const logout=useLogoutAdmin();const create=useCreateScheme();const update=useUpdateScheme();const deactivate=useDeactivateScheme();const [password,setPassword]=useState("");const [editing,setEditing]=useState<Scheme|null>(null);const [adding,setAdding]=useState(false);const [feedback,setFeedback]=useState("");const authenticated=Boolean(session.data?.authenticated);
 const invalidate=()=>{client.invalidateQueries({queryKey:getListAdminSchemesQueryKey()});client.invalidateQueries({queryKey:getGetAdminSummaryQueryKey()});client.invalidateQueries({queryKey:getListSchemesQueryKey()});client.invalidateQueries({queryKey:getGetCategoriesQueryKey()})};
 const inputOf=(s:Scheme):SchemeInput=>({name:s.name,nameTe:s.nameTe,nameHi:s.nameHi,summary:s.summary,summaryTe:s.summaryTe,summaryHi:s.summaryHi,description:s.description,descriptionTe:s.descriptionTe,descriptionHi:s.descriptionHi,category:s.category,benefits:s.benefits,eligibilitySummary:s.eligibilitySummary,documents:s.documents,applicationSteps:s.applicationSteps,officialUrl:s.officialUrl,sourceType:s.sourceType,keywords:s.keywords,active:s.active});
 const save=(data:SchemeInput)=>{if(editing)update.mutate({id:editing.id,data},{onSuccess:()=>{invalidate();setEditing(null);setFeedback(t.saveSuccess)},onError:()=>setFeedback(t.adminError)});else create.mutate({data},{onSuccess:()=>{invalidate();setAdding(false);setFeedback(t.saveSuccess)},onError:()=>setFeedback(t.adminError)})};
 return <div className="content-wrap page-enter admin-page"><PageIntro eyebrow={t.admin} title={t.adminTitle} body={t.adminIntro}/>
 {!authenticated?<section className="login-card"><span className="login-mark"><ShieldCheck/></span><span className="eyebrow">{t.demoAdminAccess}</span><h2>{t.demoSignInTitle}</h2><p>{t.demoSignInBody}</p><form onSubmit={e=>{e.preventDefault();login.mutate({data:{password} as AdminLoginInput},{onSuccess:()=>{setPassword("");client.invalidateQueries({queryKey:getAdminSessionQueryKey()});session.refetch()},onError:()=>setFeedback(t.badPassword)})}}><label className="field"><span>{t.accessCode}</span><input type="password" autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)} required data-testid="input-admin-password"/></label>{(session.isError||login.isError)&&<p className="form-error" role="alert">{feedback||t.authUnavailable}</p>}<button className="button primary" disabled={login.isPending} data-testid="button-admin-login">{login.isPending?t.loading:t.signInDemo}<ArrowRight size={17}/></button></form><small>{t.adminFootnote}</small></section>
 :<><div className="admin-toolbar"><div className="admin-stats">{summary.isLoading?<Loading label={t.loading}/>:summary.isError?<ErrorState label={t.loadError} onRetry={()=>summary.refetch()}/>:<>{[[t.total,summary.data?.total],[t.active,summary.data?.active],[t.categories,summary.data?.categories]].map(([label,value])=><div className="stat-card" key={String(label)}><span>{label}</span><b>{value}</b></div>)}</>}</div><div className="admin-actions"><button className="button primary" onClick={()=>setAdding(true)} data-testid="button-add-scheme">{t.addScheme}<ArrowRight size={17}/></button><button className="button secondary" onClick={()=>logout.mutate(undefined,{onSuccess:()=>{client.setQueryData(getAdminSessionQueryKey(),{authenticated:false,demoMode:true});client.invalidateQueries({queryKey:getAdminSessionQueryKey()});setFeedback("")}})} disabled={logout.isPending} data-testid="button-admin-logout">{logout.isPending?t.loading:t.signOut}</button></div></div>
 {feedback&&!login.isError&&<p className="success-note" role="status" data-testid="status-admin-feedback">{feedback}</p>}
 {records.isLoading?<Loading label={t.loading}/>:records.isError?<ErrorState label={t.loadError} onRetry={()=>records.refetch()}/>:records.data?.length?<div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>{t.name}</th><th>{t.category}</th><th>{t.source}</th><th>{t.status}</th><th>{t.actions}</th></tr></thead><tbody>{records.data.map(s=><tr key={s.id} data-testid={`row-admin-scheme-${s.id}`}><td><b>{s.name}</b><small>{s.id}</small></td><td>{s.category}</td><td><span className="source-dot">{s.sourceType==="verified"?t.verified:t.demo}</span></td><td><span className={`status-badge ${s.active?"active":"inactive"}`}>{s.active?t.activeStatus:t.inactiveStatus}</span></td><td className="table-actions"><button className="text-link" onClick={()=>setEditing(s)} data-testid={`button-edit-${s.id}`}>{t.edit}</button>{s.active&&<button className="text-link danger-link" onClick={()=>{if(window.confirm(`${t.deactivate} “${s.name}”?`))deactivate.mutate({id:s.id},{onSuccess:invalidate,onError:()=>setFeedback(t.adminError)})}} disabled={deactivate.isPending} data-testid={`button-deactivate-${s.id}`}>{t.deactivate}</button>}</td></tr>)}</tbody></table></div>:<div className="empty-state">{t.noAdmin}</div>}
 {adding&&<div className="modal-backdrop admin-modal-backdrop"><AdminForm initial={blankScheme()} onClose={()=>setAdding(false)} onSaved={save}/></div>}{editing&&<div className="modal-backdrop admin-modal-backdrop"><AdminForm initial={inputOf(editing)} onClose={()=>setEditing(null)} onSaved={save}/></div>}
 {(create.isPending||update.isPending)&&<p role="status">{t.loading}</p>}</>}
 </div>}

function LocalNotFound(){const t=useText();return <div className="content-wrap not-found page-enter"><span className="eyebrow">404 · GramaSeva</span><h1>{t.notFound}</h1><Link href="/" className="button primary" data-testid="link-return-home">{t.returnHome}<ArrowRight size={17}/></Link></div>}
function Router(){return <Switch><Route path="/" component={Home}/><Route path="/schemes" component={Schemes}/><Route path="/schemes/:id">{params=><SchemeDetail id={params.id}/>}</Route><Route path="/eligibility" component={Eligibility}/><Route path="/assistant" component={Assistant}/><Route path="/about" component={About}/><Route path="/admin" component={Admin}/><Route component={LocalNotFound}/></Switch>}
function App(){const [lang,setLang]=useState<Language>("en"),[large,setLarge]=useState(false),[contrast,setContrast]=useState(false);
 return <QueryClientProvider client={qc}><UiContext.Provider value={{lang,setLang,large,setLarge,contrast,setContrast}}><WouterRouter base={import.meta.env.BASE_URL.replace(/\/$/,"")}><Shell><Router/></Shell></WouterRouter></UiContext.Provider></QueryClientProvider>
}
export default App;
